### ISSUE TITLE
多余设计

### ISSUE THREAD

**Issue by fbozhang** [TencentBlueKing/bk-resource#71]
https://github.com/TencentBlueKing/bk-resource/blob/8b2401a85c34e2b02671e0184e60461fc41c0f4f/bk_resource/contrib/model.py#L53-L54

如果是继承包里自带的软删除那已经过滤`filter(is_deleted=False) `了，这里是多余过滤。如果是继承自己写的软删除比如叫`active`之类的，那么这个设计则失效。个人觉得应该由继承的软删除类来重写`get_queryset`一种开发者行为而不是被第三方sdk在不知情的时候改了

**Comment by OrenZhang** [comment]
此处 is_deleted 适配的是框架的 SoftDeleteModel，如果是框架以外的 Model，自行重写 queryset 方法
